MODEL:
  PRETRAIN_PATH:  '/home/josep/Escriptori/mtmc-vt/src/reid_baseline/export_dir/aic_track2/softmax_triplet/resnet50_model_120.pth'


INPUT:
  SIZE_TRAIN: [256,256]
  SIZE_TEST: [256,256]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('aic_track2')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 1

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 100
  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 1
  WEIGHT: /home/josep/Escriptori/mtmc-vt/src/reid_baseline/export_dir/aic_track2/softmax_triplet/resnet50_model_120.pth

OUTPUT_DIR: "export_dir/aic_track2/softmax_triplet"


